### ISSUE TITLE
Als werkzoekende, kan aangeven welke beperkingen ik heb zodat ik alleen vacatures ziet die bij mij past door middel van filteren

### ISSUE THREAD

**Issue by EllaPaulina** [QuintenVanDerBlom/TLE-Agency-Team-4#1]
Acceptatiecriteria:

- [x] Gebruiker kan een lijst met beperkingen selecteren (bijvoorbeeld fysieke, mentale of andere handicaps).

- [x] Het systeem biedt een overzicht van vacatures die overeenkomen met de geselecteerde beperkingen.
- [x] Alleen vacatures die aansluiten bij de opgegeven beperkingen worden getoond.

DOD:
- [x] Werkt volledig op desktop, tablet en smartphone.
- [x] Getest in Chrome firefox en safari.
- [x] Alle codeconventies zijn aangehouden.
- [x] Voldoet aan de huisstijl.
- [x] De totale pagina laad in minder dan een 1 seconde
- [x] Alle onderdelen op de website hebben alt-tekst zodat screenreaders deze correct kunnen voorlezen
- [x] De gehele webapp is volledig bruikbaar met een toetsenbord. Alle interactieve elementen (knoppen, links, invoervelden) moeten focusbaar zijn en in een logische volgorde navigeren.
- [x] Elk interactieve element heeft een duidelijke focusindicator (zoals een omlijning of schaduw) om zichtbaar te maken waar de gebruiker zich bevindt.
- [x] Alle invoervelden hebben een zichtbaar en expliciet label (zoals "Naam" of "E-mailadres"). Placeholder-tekst wordt alleen als aanvulling gebruikt.
- [x] Gebruik kleur niet als enige manier om informatie over te brengen (bijvoorbeeld statusindicaties).
- [x] Alle audio- en video-inhoud heeft een mogelijkheid om het geluid te dempen, het volume aan te passen, en/of te pauzeren.
- [x] Voor video-inhoud zijn ondertiteling en transcripties beschikbaar, zodat gebruikers met gehoorbeperkingen toegang hebben tot de informatie.

**Comment by ElisaZornig** [comment]
Kijk nog even goed naar de styling in onze wireframes want het komt nog niet overheen, het lijkt ook of je informatie mist zoals geboortedatum etc

**Comment by Kasperdejong** [comment]
Zorg dat je de checkboxes en de text wat groter maakt dan word het makkelijker clickable voor mensen met een beperking of oude mensen die soms een wat grotere knop / inhoud nodig hebben om op te drukken. Liefst dat de witruimte op de pagina ermee word opgevuld

**Comment by EllaPaulina** [comment]
ik heb de feedback toegepast!
